### ISSUE TITLE
labels outside of plot area

### ISSUE THREAD

**Issue by jeroenpullens** [JosephCrispell/addTextLabels#1]
Dear Joseph,

Thank you very much for this tool, it is really useful!
I was wondering if there is an option (that I have missed) to tell the function that it should not print outside the plot area?

Thank you very much!
Jeroen

**Comment by JosephCrispell** [comment]
Dear Jeroen,

Thanks for using the tool! Really glad that you find it useful. 

You've noticed an important issue. There wasn't an option to avoid printing labels outside of the plot area but I have just added that option with a new parameter (`keepLabelsInside`). Also, this will be the new default behaviour.

The `keepLabelsInside` parameter will be available if you download the latest version of the package.

Thanks very much for using the tool and let me know if the changes solve this issue.

Joseph

**Comment by jeroenpullens** [comment]
Dear Joseph,

Thank you very much for the very fast enhancement of the tool! I am pleasantly surprised by your speed and the good work!

Have a nice day!

PS. I think we can close this issue, what do you think?

**Comment by JosephCrispell** [comment]
Dear Jeroen,

Thanks to you for pointing out the issue, it's a very useful option for the tool to have and I'd been meaning to do it for a while.

Thanks again for using the tool.

Joseph
